# Generated by Django 5.2.15 on 2026-08-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='フォーム名')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='通知先')),
                ('subject', models.CharField(default='Webサイトからのお問い合わせ', max_length=180, verbose_name='通知件名')),
                ('autoresponder_subject', models.CharField(blank=True, max_length=180, verbose_name='自動返信件名')),
                ('autoresponder_body', models.TextField(blank=True, verbose_name='自動返信本文')),
                ('success_message', models.CharField(default='お問い合わせを受け付けました。', max_length=300, verbose_name='成功メッセージ')),
                ('error_message', models.CharField(default='送信できませんでした。入力内容をご確認ください。', max_length=300, verbose_name='失敗メッセージ')),
                ('retention_days', models.PositiveSmallIntegerField(default=90, verbose_name='保存日数')),
                ('is_active', models.BooleanField(default=False, verbose_name='有効')),
                ('is_archived', models.BooleanField(default=False, verbose_name='アーカイブ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '問い合わせフォーム',
                'verbose_name_plural': '問い合わせフォーム',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactPluginSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_post_bytes', models.PositiveIntegerField(default=65536, verbose_name='POST上限')),
                ('rate_limit', models.PositiveSmallIntegerField(default=5, verbose_name='IP・フォーム別上限')),
                ('rate_window_seconds', models.PositiveIntegerField(default=600, verbose_name='制限時間（秒）')),
                ('minimum_fill_seconds', models.PositiveSmallIntegerField(default=2, verbose_name='最短入力時間')),
                ('default_retention_days', models.PositiveSmallIntegerField(default=90, verbose_name='既定保存日数')),
            ],
            options={
                'verbose_name': '問い合わせフォーム設定',
                'verbose_name_plural': '問い合わせフォーム設定',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='送信内容')),
                ('status', models.CharField(choices=[('received', '受付済み'), ('delivered', '通知済み'), ('mail_failed', 'メール失敗')], default='received', max_length=20)),
                ('ip_hash', models.CharField(max_length=64, verbose_name='IPハッシュ')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='User-Agent')),
                ('page_path', models.CharField(blank=True, max_length=500, verbose_name='送信元ページ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='contact_forms.contactform')),
            ],
            options={
                'verbose_name': '問い合わせ履歴',
                'verbose_name_plural': '問い合わせ履歴',
                'ordering': ('-submitted_at',),
                'permissions': [('view_contact_content', '問い合わせ本文を閲覧できる'), ('export_contact_submission', '問い合わせをCSV出力できる')],
            },
        ),
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='項目キー')),
                ('label', models.CharField(max_length=120, verbose_name='表示名')),
                ('kind', models.CharField(choices=[('text', '1行テキスト'), ('email', 'メール'), ('tel', '電話番号'), ('textarea', '複数行テキスト'), ('number', '数値'), ('date', '日付'), ('select', 'セレクトボックス'), ('radio', 'ラジオボタン'), ('checkbox', 'チェックボックス'), ('consent', '個人情報取扱いへの同意')], max_length=20, verbose_name='種類')),
                ('required', models.BooleanField(default=False, verbose_name='必須')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='選択肢')),
                ('max_length', models.PositiveIntegerField(default=200, verbose_name='最大文字数')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='並び順')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contact_forms.contactform')),
            ],
            options={
                'verbose_name': '入力項目',
                'verbose_name_plural': '入力項目',
                'ordering': ('order', 'pk'),
                'unique_together': {('form', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('notification', '管理者通知'), ('autoreply', '自動返信')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '送信待ち'), ('sent', '送信済み'), ('failed', '失敗')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='contact_forms.contactsubmission')),
            ],
            options={
                'verbose_name': 'メール送信結果',
                'verbose_name_plural': 'メール送信結果',
                'unique_together': {('submission', 'kind')},
            },
        ),
    ]
